/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import com.mycompany.arboldecision.Arbol;
import com.mycompany.arboldecision.Nodo;
import java.util.ArrayList;
import java.util.Map;

/**
 *
 * @author Yiro
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    Arbol a = new Arbol();
    int numList = 0;
    ArrayList<Integer> listaRespuestas = new ArrayList();
    
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enfermedadField = new javax.swing.JTextField();
        sintomaField = new javax.swing.JTextField();
        registrarButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        diagnosticoBox = new javax.swing.JComboBox<>();
        diagnosticoButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        diagnosticoField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        diagnosticoFieldPreguntas = new javax.swing.JTextField();
        comenzarButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enfermedadField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        signoField = new javax.swing.JTextField();
        registrarButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 51));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese enfermedad:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ingrese sintoma:");

        enfermedadField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enfermedadField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfermedadFieldActionPerformed(evt);
            }
        });

        sintomaField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sintomaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sintomaFieldActionPerformed(evt);
            }
        });

        registrarButton.setBackground(new java.awt.Color(102, 255, 102));
        registrarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registrarButton.setText("Registrar");
        registrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("REGISTRO DE ENFERMEDADES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registrarButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(41, 41, 41))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(65, 65, 65)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sintomaField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enfermedadField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(enfermedadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sintomaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(registrarButton)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro de sintomas", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        diagnosticoBox.setBackground(new java.awt.Color(102, 255, 102));
        diagnosticoBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        diagnosticoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        diagnosticoButton.setBackground(new java.awt.Color(102, 255, 102));
        diagnosticoButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        diagnosticoButton.setText("Evaluar");
        diagnosticoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosticoButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Resultado:");

        diagnosticoField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        diagnosticoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosticoFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("DIAGNOSTICO");

        diagnosticoFieldPreguntas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        diagnosticoFieldPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosticoFieldPreguntasActionPerformed(evt);
            }
        });

        comenzarButton.setBackground(new java.awt.Color(102, 255, 102));
        comenzarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comenzarButton.setText("Comenzar");
        comenzarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(221, 221, 221))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(diagnosticoFieldPreguntas, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(diagnosticoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(169, 169, 169)
                                    .addComponent(diagnosticoButton)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comenzarButton))
                        .addComponent(diagnosticoField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diagnosticoFieldPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comenzarButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diagnosticoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diagnosticoButton))
                .addGap(84, 84, 84)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diagnosticoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Diagnostico", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("REGISTRO DE ENFERMEDADES");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese enfermedad:");

        enfermedadField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enfermedadField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfermedadField1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Ingrese signo:");

        signoField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoFieldActionPerformed(evt);
            }
        });

        registrarButton1.setBackground(new java.awt.Color(102, 255, 102));
        registrarButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registrarButton1.setText("Registrar");
        registrarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registrarButton1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(41, 41, 41))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(65, 65, 65)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(signoField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enfermedadField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(enfermedadField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(signoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(registrarButton1)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro de signos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enfermedadFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfermedadFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enfermedadFieldActionPerformed

    private void sintomaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sintomaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sintomaFieldActionPerformed

    private void registrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarButtonActionPerformed
        Nodo nodo = new Nodo(sintomaField.getText(),enfermedadField.getText());
        a.agregar(nodo);
        sintomaField.setText("");
        enfermedadField.setText("");
    }//GEN-LAST:event_registrarButtonActionPerformed

    private void diagnosticoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosticoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diagnosticoFieldActionPerformed

    private void enfermedadField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfermedadField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enfermedadField1ActionPerformed

    private void signoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signoFieldActionPerformed

    private void registrarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarButton1ActionPerformed
        Nodo nodo = new Nodo(signoField.getText(),enfermedadField1.getText());
        a.agregar(nodo);
        signoField.setText("");
        enfermedadField1.setText("");
    }//GEN-LAST:event_registrarButton1ActionPerformed

    private void diagnosticoFieldPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosticoFieldPreguntasActionPerformed
        
    }//GEN-LAST:event_diagnosticoFieldPreguntasActionPerformed

    private void comenzarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarButtonActionPerformed
        a.crearArbol();
        listaRespuestas.clear();
        diagnosticoField.setText("");

        numList = 0;
        if(a.getTamanio() == numList){
          diagnosticoFieldPreguntas.setText("");  
        }else{
            String sintoma = a.getNodo(numList).getSintoma();
            diagnosticoFieldPreguntas.setText("Tienes " + sintoma + "?");
        }
    }//GEN-LAST:event_comenzarButtonActionPerformed

    private void diagnosticoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosticoButtonActionPerformed
        
        String opcion = diagnosticoBox.getSelectedItem().toString();
        if(a.getTamanio() == 0){
            return;
        }
        if(opcion.equals("Si")){
            if(numList < a.getTamanio() - 1){
                numList++;
                String sintoma = a.getNodo(numList).getSintoma();
                diagnosticoFieldPreguntas.setText("Tienes " + sintoma + "?");
                listaRespuestas.add(1);
            }else {
                listaRespuestas.add(1);
                diagnosticoFieldPreguntas.setText("");
                numList++;
            }
            
        }else {
            if(numList < a.getTamanio() - 1){
                numList++;
                String sintoma = a.getNodo(numList).getSintoma();
                diagnosticoFieldPreguntas.setText("Tienes " + sintoma + "?");
                listaRespuestas.add(2);
            }else {
                listaRespuestas.add(2);
                diagnosticoFieldPreguntas.setText("");
                numList++;
            }
        }
        if(numList == a.getTamanio()){
            diagnosticoField.setText(a.clasificar(listaRespuestas));
        }
    }//GEN-LAST:event_diagnosticoButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comenzarButton;
    private javax.swing.JComboBox<String> diagnosticoBox;
    private javax.swing.JButton diagnosticoButton;
    private javax.swing.JTextField diagnosticoField;
    private javax.swing.JTextField diagnosticoFieldPreguntas;
    private javax.swing.JTextField enfermedadField;
    private javax.swing.JTextField enfermedadField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton registrarButton;
    private javax.swing.JButton registrarButton1;
    private javax.swing.JTextField signoField;
    private javax.swing.JTextField sintomaField;
    // End of variables declaration//GEN-END:variables
}
